### ISSUE TITLE
リンク切れ

### ISSUE THREAD

**Issue by chao7150** [yuchiki/yuchiki.github.io#1]
https://github.com/yuchiki/yuchiki.github.io/blob/c59a23d5caab7aa00355e645b94bd3c91d378218/src/profile/index.haml#L107

**Comment by yuchiki** [comment]
ご指摘ありがとうございます。
[こちらのコミット](https://github.com/yuchiki/yuchiki.github.io/commit/6ab0caf00660cf51ec20041dff6e0a9d6082d370)で修正しました。
